name: pretty_dio_logger
description: Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
version: 2.0.1
homepage: https://github.com/Milad-Akarie/pretty_dio_logger

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  dio: ^4.0.0-beta2
